# Generated by Django 5.1.7 on 2025-04-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_casestudies'),
        ('api', '0012_howwedo_whymeta'),
    ]

    operations = [
    ]
