# Generated by Django 5.1.7 on 2025-04-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0011_casestudies_0012_howwedo_whymeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howwedo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/howWeDo/'),
        ),
    ]
