# Generated by Django 5.1.7 on 2025-04-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_howwedo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUxUi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/howWeDo/')),
            ],
        ),
    ]
