# Generated by Django 5.1.7 on 2025-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aboutuxui'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUxUi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/uxUi/')),
            ],
        ),
        migrations.CreateModel(
            name='UiServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/uxUi/')),
            ],
        ),
        migrations.CreateModel(
            name='UxServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/uxUi/')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutuxui',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/uxUi/'),
        ),
    ]
