# Generated by Django 5.1.7 on 2025-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_addsoftware_advantagessoftdev_advantagesstaff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/ourServices/')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUxUi',
        ),
    ]
