# Generated by Django 5.1.7 on 2025-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_location_delete_ourlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageteam',
            name='position',
            field=models.CharField(default='Member', max_length=100),
        ),
    ]
