# Generated by Django 5.1.7 on 2025-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_location_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourdataapproach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/dataScienceServ/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
