# Generated by Django 5.1.7 on 2025-04-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_ourdataapproach_image_alter_location_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/machineLearning/')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('headCount', models.PositiveIntegerField()),
                ('office', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
