# Generated by Django 5.1.7 on 2025-04-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_applicantsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantsPositionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicantsDetails',
        ),
    ]
