# Generated by Django 5.1.7 on 2025-04-28 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_getintouch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getintouch',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='getintouch',
            name='created_at',
        ),
        migrations.AddField(
            model_name='getintouch',
            name='interest',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
