# Generated by Django 5.1.7 on 2025-04-28 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_name_getintouch_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
