# Generated by Django 5.1.7 on 2025-04-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_getintouch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantspositiondetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
