# Generated by Django 5.1.7 on 2025-05-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
